### ISSUE TITLE
Prisma Client Not Generating on Vercel Deployment

### ISSUE THREAD

**Issue by bishae** [bishae/planner#1]
### Problem Statement

When deploying my application to Vercel, I am encountering an issue where Prisma Client is not being generated as expected. Prisma Client is a crucial component of my application, and its absence is causing my application to malfunction.

#### Expected Behavior

1. Prisma Client should be automatically generated during the deployment process.
2. The application should deploy and function correctly with the generated Prisma Client.

#### Current Behavior

1. Prisma Client is not being generated as expected during deployment.
2. This leads to errors during deployments, causing the following error output.

```
[21:53:10.910] Running build in Washington, D.C., USA (East) – iad1 (Hive)
[21:53:11.013] Cloning github.com/bishae/planner (Branch: main, Commit: a4427ee)
[21:53:11.293] Cloning completed: 279.69ms
[21:53:16.586] Restored build cache
[21:53:16.660] Running "vercel build"
[21:53:17.096] Vercel CLI 32.4.1
[21:53:17.452] Detected `pnpm-lock.yaml` version 6 generated by pnpm 8
[21:53:17.470] Installing dependencies...
[21:53:18.070] Lockfile is up to date, resolution step is skipped
[21:53:18.115] Progress: resolved 1, reused 0, downloaded 0, added 0
[21:53:18.181] Packages: +4
[21:53:18.181] ++++
[21:53:18.662] Progress: resolved 4, reused 0, downloaded 4, added 4, done
[21:53:18.961] .../node_modules/@prisma/engines postinstall$ node scripts/postinstall.js
[21:53:19.743] .../node_modules/@prisma/engines postinstall: Done
[21:53:19.931] .../prisma@5.5.2/node_modules/prisma preinstall$ node scripts/preinstall-entry.js
[21:53:19.990] .../prisma@5.5.2/node_modules/prisma preinstall: Done
[21:53:20.114] .../node_modules/@prisma/client postinstall$ node scripts/postinstall.js
[21:53:20.972] .../node_modules/@prisma/client postinstall: Prisma schema loaded from prisma/schema.prisma
[21:53:21.452] .../node_modules/@prisma/client postinstall: ✔ Generated Prisma Client (v5.5.2) to ./node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client in 60ms
[21:53:21.453] .../node_modules/@prisma/client postinstall: Start using Prisma Client in Node.js (See: https://pris.ly/d/client)
[21:53:21.453] .../node_modules/@prisma/client postinstall: ```
[21:53:21.454] .../node_modules/@prisma/client postinstall: import { PrismaClient } from '@prisma/client'
[21:53:21.454] .../node_modules/@prisma/client postinstall: const prisma = new PrismaClient()
[21:53:21.454] .../node_modules/@prisma/client postinstall: ```
[21:53:21.455] .../node_modules/@prisma/client postinstall: or start using Prisma Client at the edge (See: https://pris.ly/d/accelerate)
[21:53:21.455] .../node_modules/@prisma/client postinstall: ```
[21:53:21.455] .../node_modules/@prisma/client postinstall: import { PrismaClient } from '@prisma/client/edge'
[21:53:21.455] .../node_modules/@prisma/client postinstall: const prisma = new PrismaClient()
[21:53:21.456] .../node_modules/@prisma/client postinstall: ```
[21:53:21.456] .../node_modules/@prisma/client postinstall: See other ways of importing Prisma Client: http://pris.ly/d/importing-client
[21:53:21.498] .../node_modules/@prisma/client postinstall: Done
[21:53:21.977] 
[21:53:21.977] dependencies:
[21:53:21.977] + @prisma/client 5.5.2
[21:53:21.977] 
[21:53:21.977] devDependencies:
[21:53:21.980] + prisma 5.5.2
[21:53:21.980] 
[21:53:22.042] Done in 4.5s
[21:53:22.067] Detected Next.js version: 13.5.6
[21:53:22.075] Running "pnpm run build"
[21:53:22.586] 
[21:53:22.586] > planner@0.1.1 build /vercel/path0
[21:53:22.586] > next build
[21:53:22.587] 
[21:53:23.382]    Creating an optimized production build ...
[21:53:28.960]  ✓ Compiled successfully
[21:53:28.961]    Linting and checking validity of types ...
[21:53:31.990]    Collecting page data ...
[21:53:32.550] Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
[21:53:32.551] 
[21:53:32.551] Learn how: https://pris.ly/d/vercel-build
[21:53:32.553] PrismaClientInitializationError: Prisma has detected that this project was built on Vercel, which caches dependencies. This leads to an outdated Prisma Client because Prisma's auto-generation isn't triggered. To fix this, make sure to run the `prisma generate` command during the build process.
[21:53:32.553] 
[21:53:32.553] Learn how: https://pris.ly/d/vercel-build
[21:53:32.553]     at xa (/vercel/path0/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:36:69)
[21:53:32.554]     at new t (/vercel/path0/node_modules/.pnpm/@prisma+client@5.5.2_prisma@5.5.2/node_modules/@prisma/client/runtime/library.js:128:2640)
[21:53:32.554]     at 7917 (/vercel/path0/.next/server/app/tasks/page.js:1:2110)
[21:53:32.554]     at Function.__webpack_require__ (/vercel/path0/.next/server/webpack-runtime.js:1:145)
[21:53:32.554]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[21:53:32.554]     at async collectGenerateParams (/vercel/path0/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:859:17) {
[21:53:32.554]   clientVersion: '5.5.2',
[21:53:32.554]   errorCode: undefined
[21:53:32.554] }
[21:53:32.555] 
[21:53:32.555] > Build error occurred
[21:53:32.557] Error: Failed to collect page data for /tasks
[21:53:32.557]     at /vercel/path0/node_modules/.pnpm/next@13.5.6_react-dom@18.2.0_react@18.2.0/node_modules/next/dist/build/utils.js:1171:15
[21:53:32.558]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
[21:53:32.558]   type: 'Error'
[21:53:32.558] }
[21:53:32.598]  ELIFECYCLE  Command failed with exit code 1.
[21:53:32.615] Error: Command "pnpm run build" exited with 1
```

**Comment by bishae** [comment]
With the `postinstall` script, the issue is elegantly resolved. Here's how it works:

1. In the `package.json` file, we specify a `postinstall` script that runs after `npm install` or `yarn install`.

2. Within this `postinstall` script, we include a command to automatically generate the Prisma Client code based on the latest database schema.

3. This ensures that whenever we install or update dependencies, the Prisma Client is always up to date and synchronized with the database schema without any manual intervention.

This not only simplifies the development process but also improves the overall robustness and reliability of applications that use Prisma Client, as the data access layer is always in sync with the database.

Example `postinstall` script in `package.json`:
```json
"scripts": {
  "postinstall": "npx prisma generate"
}
